version: '3.7'

services:
  php-fpm:
    build:
      context: ./
      target: prod
      dockerfile: .docker/docker/php/build.docker
      args:
        VERSION: 7.3-fpm
    image: project:7.3-fpm
    volumes:
      - ./:/project
    networks:
      - project
    env_file:
      - .docker.env.dist
      - .docker.env

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/data:rw
      - .docker/prod/db/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - project
    ports:
      - "5432:5432"
    env_file:
      - .docker.env.dist
      - .docker.env

  nginx:
    image: nginx:latest
    volumes:
      - ./:/project
      - ./.docker/prod/nginx/etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .docker.env.dist
      - .docker.env

volumes:
  db_data: {}

networks:
  project: {}
