version: '3.7'

services:
  php-fpm:
    build:
      context: ./
      target: prod
      dockerfile: .docker/docker/php/build.docker
      args:
        VERSION: 7.3-fpm
    image: project:7.3-fpm
    cap_drop:
      - ALL
    volumes:
      - ./:/project
    networks:
      - project

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/data
      - .docker/prod/db/scripts:/docker-entrypoint-initdb.d
    networks:
      - project
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
      POSTGRES_DB: project
      PGDATA: /var/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./:/project
      - ./.docker/prod/nginx/etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - project

volumes:
  db_data: {}

networks:
  project: {}
